=== dolauli/azure-powershell/portal-metadata/Compute/developerInputSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
      "resourceType": {
        "type": "string"
      },
      "apiVersion": {
        "type": "string"
      },
      "learnMore": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string"
          }
        }
      },
      "pathParameters": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "swaggerName": {
              "type": "string"
            },
            "cmdletParameter": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "swaggerName",
            "cmdletParameter"
          ]
        }
      },
      "commands": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "resourceType",
      "apiVersion",
      "pathParameters",
      "commands"
    ]
  }

=== dolauli/azure-powershell/portal-metadata/Compute/developerInput.json
{
    "resourceType": "workspaces",
    "apiVersion": "2021-04-01-preview",
    "learnMore": {
        "url": "https://docs.microsoft.com/powershell/module/az.databricks"
    },
    "pathParameters": [
        {"swaggerName": "subscriptionId",
         "cmdletParameter": ["SubscriptionId"]
        },
        {"swaggerName": "resourceGroupName",
         "cmdletParameter": ["ResourceGroupName"]
        },
        {"swaggerName": "workspaceName",
         "cmdletParameter": ["Name"]
        }
    ],
    "commands": [
        "Get-AzDatabricksWorkspace", "Remove-AzDatabricksWorkspace"
    ]
}
